networks:
  nginx-proxy:
    external: true
    
services:
  dolar-react:
    build:
      context: ./frontend
    container_name: dolar_react
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=dolar.juanbogado.dev
      - LETSENCRYPT_HOST=dolar.juanbogado.dev
      - LETSENCRYPT_EMAIL=juanjosebogado93@gmail.com
      - VIRTUAL_PORT=80
    volumes:
      - ./diario.json:/app/diario.json 
      - ../nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
    networks:
      - nginx-proxy
    depends_on:
      - db
    restart: always


  api:
    build: 
      context: .
      target: django
    container_name: dolar_app
    expose:
      - "8004" 
    environment:
      - VIRTUAL_HOST=api.juanbogado.dev
      - LETSENCRYPT_HOST=api.juanbogado.dev
      - LETSENCRYPT_EMAIL=juanjosebogado93@gmail.com
      - VIRTUAL_PORT=8004
    volumes:
      - ./diario.json:/app/diario.json 
    networks:
      - nginx-proxy
    depends_on:
      - db
    restart: always
    

  cron-job:
    build:
      context: .
      target: cron
    container_name: cron
    volumes:
      - ./diario.json:/app/diario.json
      - ./logs:/var/log/cron
    networks:
      - nginx-proxy
    depends_on:
      - db
      - api
    restart: always


  db:
    image: postgres
    container_name: cotizacion-db    
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nginx-proxy
    restart: always

volumes:
  postgres_data:
    